name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Building
        run: sudo apt install openjdk-8-jdk && chmod +x ./gradlew && ./gradlew build
      - name: Uploading
        uses: actions/upload-artifact@v4.3.3
        with:
          path: build/

