name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Building
        run: sudo apt install gradle java && chmod +x gradlew && java -jar gradle/wrapper/gradle-wrapper.jar --gradle-version=5.11 && ./gradlew setupDevWorkspace && ./gradlew eclipse
