name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Building
        run: sudo apt install openjdk-11-jdk openjdk-8-demo openjdk-11-doc openjdk-11-jre-headless openjdk-11-source && chmod +x ./gradlew && ./gradlew setupDevWorkspace && ./gradlew eclipse
