name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Building
        run: chmod gradlew +x
             ./gradlew setupDecompWorkspace
             ./gradlew eclipse
